[project]
name = "codectl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.25.0",
    "pytest>=9.0.2",
    "smolagents[litellm]>=1.24.0",
    "tree-sitter>=0.25.2",
    "tree-sitter-python>=0.25.0",
]
